# SQLite. Versions 3.8.0
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3

# PostgreSQL. Versions 9.3
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: hungton
  password: hH123

development:
  <<: *default
  database: freec_test

test:
  <<: *default
  database: freec_test

production:
  <<: *default
  database: freec_test